# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_User(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(807, 540)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.UserName = QtWidgets.QLabel(Form)
        self.UserName.setGeometry(QtCore.QRect(250, 20, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(20)
        self.UserName.setFont(font)
        self.UserName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.UserName.setAutoFillBackground(False)
        self.UserName.setStyleSheet("background: None;")
        self.UserName.setText("")
        self.UserName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UserName.setObjectName("UserName")
        self.WriteButton = QtWidgets.QPushButton(Form)
        self.WriteButton.setGeometry(QtCore.QRect(40, 40, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(19)
        self.WriteButton.setFont(font)
        self.WriteButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.WriteButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(50, 50, 50, 255))")
        self.WriteButton.setObjectName("WriteButton")
        self.SentButton = QtWidgets.QPushButton(Form)
        self.SentButton.setGeometry(QtCore.QRect(40, 140, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(18)
        self.SentButton.setFont(font)
        self.SentButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SentButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(50, 50, 50, 255))")
        self.SentButton.setObjectName("SentButton")
        self.LogOutButton = QtWidgets.QPushButton(Form)
        self.LogOutButton.setGeometry(QtCore.QRect(40, 440, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(18)
        self.LogOutButton.setFont(font)
        self.LogOutButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LogOutButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(50, 50, 50, 255))")
        self.LogOutButton.setObjectName("LogOutButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(270, 100, 511, 401))
        self.tableWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 150), stop:1 rgba(0, 0, 0, 100))")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.UpdateButton = QtWidgets.QPushButton(Form)
        self.UpdateButton.setGeometry(QtCore.QRect(270, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(18)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.UpdateButton.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.UpdateButton.setText("")
        self.UpdateButton.setObjectName("UpdateButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.WriteButton.setText(_translate("Form", "Write a messege"))
        self.SentButton.setText(_translate("Form", "Sent messeges"))
        self.LogOutButton.setText(_translate("Form", "Log out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_User()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
